# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: poc-salt

steps:
- script: bash $(Pipeline.Workspace)/s/scripts/sync_master_files.sh $(Pipeline.Workspace)
  displayName: 'Syncronize Salt files'